import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer/Footer'
import Header from '../components/Header/Header'
import Main from '../components/Main/Main'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      {/* <div className={styles.container}> */}
        <Head>
          <title>NFT Marketplace</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logos/favicon.png" />
        </Head>

        <Header />
        <Main />
        <Footer />
      {/* </div> */}
    </>
  )
}
